"""Write the files and open the pull request -- a resumable transaction, run by script not model.

Two reasons this is code rather than something the writing agent does:

* **It is the arbiter.** The model produces prose and nothing else; every mechanical step -- what
  the files contain, which paths change, what the commit says, which branch it lands on -- happens
  here, where it is tested. That is what makes "scripts decide everything decidable" true rather
  than aspirational.

* **It has to survive interruption.** `push` then `gh pr create` is two operations, and a worker can
  die between them, or lose the response to the second after GitHub has acted on it. A naive retry
  then either wedges on an existing branch or opens a duplicate. So the branch name is a pure
  function of the window, and every run reconciles what already exists before doing anything:

      no branch, no PR      -> commit, push, create
      branch, no PR         -> reuse the branch (update if the content differs), create
      open PR               -> in flight; do nothing
      merged PR             -> already done; do nothing
      closed, unmerged PR   -> someone rejected this window; do NOT reopen, report loudly

The last case matters: a rejected report must not come back by itself every day.
"""

import json
import pathlib
import subprocess

from . import files, gh, window

BRANCH_PREFIX = "progress/"
# Recorded in the PR body so a reader (and the merge gate) can tell which TauCetiProgress produced
# it. The gate, the worker and this module must all run the same version; see README.md.
BODY_MARKER = "<!--tauceti-progress-pr:v1 {}-->"

EX_NOPROGRESS = 75


class ApplyError(RuntimeError):
    pass


def branch_name(plan):
    """`progress/<from7>-<to7>/<Area>`: a pure function of the window.

    Determinism is the whole point -- two workers computing the same window compute the same branch,
    so the second one finds the first one's work instead of duplicating it.
    """
    return f"{BRANCH_PREFIX}{plan['from_sha'][:7]}-{plan['to_sha'][:7]}/{plan['roadmap']}"


def pr_title(plan):
    """`progress: <Area> <date>`.

    The `progress:` prefix is load-bearing beyond readability: a squash merge carries the PR title
    into the commit subject, and the cheap `due` check finds the last update by scanning roadmap
    commit subjects for exactly this prefix.
    """
    date = (plan.get("to_date") or "")[:10]
    return f"progress: {plan['roadmap']} report for {date}".rstrip()


def pr_body(plan, section_header, version=None):
    """The PR description: what this covers, and enough metadata to audit it."""
    prs = ", ".join(f"#{n}" for n in sorted(plan["prs"]))
    meta = {
        "roadmap": plan["roadmap"],
        "from_sha": plan["from_sha"],
        "to_sha": plan["to_sha"],
        "prs": sorted(plan["prs"]),
        "version": version,
    }
    return (
        f"{BODY_MARKER.replace('{}', json.dumps(meta, sort_keys=True, separators=(',', ':')))}\n"
        f"This PR records progress on the {plan['roadmap']} roadmap for the window "
        f"`{plan['from_sha'][:7]}..{plan['to_sha'][:7]}` of TauCeti `main`, covering "
        f"{len(plan['prs'])} merged pull requests.\n\n"
        f"`STATUS.md` is rewritten as a snapshot at `{plan['to_sha'][:7]}`; `PROGRESS.md` gains one "
        f"appended section for the window. Both files are machine-owned and their prose is not "
        f"security-validated.\n\n"
        f"Pull requests in the window: {prs}\n\n"
        f"Generated by [TauCetiProgress](https://github.com/TauCetiProject/TauCetiProgress)"
        f"{f' at `{version}`' if version else ''}.\n\n"
        f"🤖 Prepared with Claude Code\n"
    )


def _run(args, cwd, check=True):
    proc = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True)
    if check and proc.returncode != 0:
        raise ApplyError(f"{' '.join(args)} failed: {proc.stderr.strip() or proc.returncode}")
    return proc


def _own_login():
    """The authenticated login, for scoping "did *I* already try this window?" lookups."""
    return gh.gh(["api", "user", "--jq", ".login"]).strip()


def own_closed_pr(branch, repo=gh.ROADMAP_REPO):
    """A closed-unmerged pull request for `branch` that this operator could have opened, or None.

    "Could have opened" means its head is either in the canonical repository (we pushed there) or in
    an account we control. Deliberately not "any closed pull request on this branch": see the caller.

    Checked without consulting `push_target`, so that a dry run never has to create a fork just to
    answer a question about existing pull requests.
    """
    out = gh.gh([
        "pr", "list", "--repo", repo, "--head", branch, "--state", "closed",
        "--limit", "20", "--json", "number,state,url,mergedAt,headRepositoryOwner",
    ])
    ours = {repo.split("/")[0], _own_login()}
    for row in json.loads(out):
        if row.get("mergedAt"):
            continue
        if ((row.get("headRepositoryOwner") or {}).get("login") or "") in ours:
            return row
    return None


def existing_pr(branch, repo=gh.ROADMAP_REPO, owner=None, states=("open",)):
    """A pull request for `branch`, or None.

    Anyone may open a pull request on a progress branch, and branch names are a pure function of the
    window, so `--head <branch>` matches strangers' pull requests as readily as our own. Two of the
    ways this function is used therefore have to be told whose work to look at:

    * Deciding "has this window already been proposed?" must consider EVERYONE, or two operators
      duplicate each other. Open ones only.
    * Deciding "was this window refused, so stop reopening it?" must consider only OUR OWN, or a
      stranger can open and immediately close a pull request on the deterministic branch name and
      permanently stop that window from ever being published. Closed-state matching is scoped by
      `owner` for exactly that reason.
    """
    head = f"{owner}:{branch}" if owner else branch
    rows = []
    for state in states:
        out = gh.gh([
            "pr", "list", "--repo", repo, "--head", head, "--state", state,
            "--limit", "20", "--json", "number,state,url,mergedAt,headRepositoryOwner",
        ])
        rows.extend(json.loads(out))
    return rows[0] if rows else None


def remote_branch_exists(roadmap_dir, branch, remote="origin"):
    proc = _run(["git", "ls-remote", "--exit-code", "--heads", remote, branch],
               roadmap_dir, check=False)
    return proc.returncode == 0


def push_target(roadmap_dir, repo=gh.ROADMAP_REPO):
    """Where to push the report branch: `(remote_name, head_ref_for_pr)`.

    Publishing is open to anyone, so most operators will not have push access to the roadmap
    repository. They publish the ordinary way an outside contributor does, from a fork, and the merge
    check accepts fork heads: it never checks out pull-request content, and a fork's head commit and
    tree are replicated into the base repository, so the merge still builds from the validated bytes.

    Push access is checked rather than assumed because pushing to the canonical repository is
    preferable when it is available -- no fork to keep alive, and the branch is deleted after the
    merge -- and because discovering the answer by failing the push would waste the whole round.
    """
    if gh.gh(["api", f"repos/{repo}", "--jq", ".permissions.push"]).strip() == "true":
        return "origin", None

    # `--jq` emits raw values, not JSON: a login comes back as `kim-em`, unquoted. Do not `json.loads`
    # it -- that raises, and this is precisely the path an operator without push access takes.
    login = gh.gh(["api", "user", "--jq", ".login"]).strip()
    if not login:
        raise RuntimeError("could not determine the authenticated login, so no fork can be used")
    # Ask the API what the fork is actually called rather than assuming `<login>/<name>`. A fork may
    # be renamed, and a guessed path can redirect today and resolve to an unrelated repository later.
    # `--clone=false` is idempotent: it creates the fork if absent and is a no-op if it exists.
    gh.gh(["repo", "fork", repo, "--clone=false", "--remote=false"])
    fork = gh.gh(["api", f"repos/{repo}/forks?per_page=100", "--jq",
                  f'[.[] | select(.owner.login == "{login}")] | .[0].full_name // ""']).strip()
    if not fork:
        # A fork the listing does not show (it is paginated and ordered by creation) is still
        # addressable by the conventional path; verify it exists before trusting it.
        candidate = f"{login}/{repo.split('/')[-1]}"
        fork = gh.gh(["api", f"repos/{candidate}", "--jq", ".full_name"]).strip()
    if not fork or "/" not in fork:
        raise RuntimeError(f"could not identify {login}'s fork of {repo}")
    url = f"https://github.com/{fork}.git"
    if _run(["git", "remote", "get-url", "fork"], roadmap_dir, check=False).returncode == 0:
        _run(["git", "remote", "set-url", "fork", url], roadmap_dir)
    else:
        _run(["git", "remote", "add", "fork", url], roadmap_dir)
    print(f"no push access to {repo}; publishing from {fork}")
    return "fork", fork.split("/")[0]


def render_update(plan, status_body, section_body, old_status, old_progress):
    """Build both files and validate them. Returns `(status_text, progress_text, section_header)`.

    Validation runs here, before anything is committed, so a malformed generation fails on the
    worker rather than becoming a pull request the gate has to reject.
    """
    area = plan["roadmap"]
    window_label = f"{(plan.get('from_date') or '')[:10]} to {(plan.get('to_date') or '')[:10]}"

    status_text = files.render_status(area, plan["to_sha"], plan.get("to_date") or "", status_body)
    section = files.render_section(
        area, plan["from_sha"], plan["to_sha"], plan["prs"], window_label, section_body
    )
    base_progress = old_progress if old_progress is not None else files.new_progress_file(area)
    progress_text = base_progress + section

    header = files.validate_update(
        area, old_status, status_text, base_progress, progress_text,
        expect_from_sha=plan["from_sha"],
    )
    return status_text, progress_text, header


def run(plan, status_body_file, section_body_file, roadmap_dir, dry_run=False, version=None):
    """Write, commit, push and open the PR. Returns a process exit code."""
    roadmap_dir = pathlib.Path(roadmap_dir)
    branch = branch_name(plan)

    # --- reconcile before acting ---------------------------------------------------------------
    # Anyone's OPEN or MERGED pull request for this window counts: it is already published or in
    # flight, and a second one would only duplicate it.
    pr = existing_pr(branch, states=("open", "merged"))
    if pr is not None:
        state = (pr.get("state") or "").upper()
        if state == "MERGED":
            print(f"already merged: {pr['url']}")
            return EX_NOPROGRESS
        print(f"already open, in flight: {pr['url']}")
        return EX_NOPROGRESS

    # A CLOSED pull request means this window was refused, and reopening it every day is the loop
    # this design avoids -- but only one WE could have opened may say so. Branch names are a pure
    # function of the window, so anyone can open and instantly close a pull request on that name;
    # honouring a stranger's would let them stop a window being published, permanently and silently.
    mine = own_closed_pr(branch)
    if mine is not None:
        print(
            f"this window was already proposed and closed unmerged ({mine['url']}); "
            f"refusing to reopen it. Land or delete that PR to unblock the area."
        )
        return EX_NOPROGRESS

    status_body = pathlib.Path(status_body_file).read_text(encoding="utf-8")
    section_body = pathlib.Path(section_body_file).read_text(encoding="utf-8")

    rel = plan["rel_dir"]
    status_path = roadmap_dir / plan["status_path"]
    progress_path = roadmap_dir / plan["progress_path"]
    if not (roadmap_dir / rel).is_dir():
        raise ApplyError(f"{rel} is not a directory in {roadmap_dir}")

    old_status = status_path.read_text(encoding="utf-8") if status_path.is_file() else None
    old_progress = progress_path.read_text(encoding="utf-8") if progress_path.is_file() else None

    status_text, progress_text, header = render_update(
        plan, status_body, section_body, old_status, old_progress
    )

    # --- commit on the deterministic branch ----------------------------------------------------
    _run(["git", "checkout", "-q", "-B", branch, "origin/main"], roadmap_dir)
    status_path.write_text(status_text, encoding="utf-8")
    progress_path.write_text(progress_text, encoding="utf-8")
    # Add only the two paths: an `add -A` here could sweep up anything else in the clone, and the
    # gate would (correctly) refuse the result.
    _run(["git", "add", "--", plan["status_path"], plan["progress_path"]], roadmap_dir)

    changed = _run(["git", "diff", "--cached", "--name-only"], roadmap_dir).stdout.split()
    if sorted(changed) != sorted([plan["status_path"], plan["progress_path"]]):
        raise ApplyError(f"staged paths are {changed}, expected exactly the two generated files")

    title = pr_title(plan)
    body = pr_body(plan, header, version=version)
    _run(["git", "commit", "-q", "-m", title, "-m", f"Window {plan['from_sha'][:7]}..{plan['to_sha'][:7]}"],
         roadmap_dir)

    if dry_run:
        diff = _run(["git", "show", "--stat", "--format=%s", "HEAD"], roadmap_dir).stdout
        print(f"[dry-run] branch {branch}\n{diff}")
        return 0

    # The branch already existing means a previous run (ours, or a peer racing us for the same window)
    # got this far and then died before opening the pull request. Leave its content alone and just open
    # the pull request for it: the branch name is a pure function of the window, so whatever is there is
    # a valid report for exactly this window, and overwriting it could clobber a peer's push moments
    # after it happened. Only push when nothing is there, and create-only so a concurrent push loses
    # rather than being silently overwritten.
    # Resolved here, after the dry-run return, because it can create a fork as a side effect.
    remote, fork_owner = push_target(roadmap_dir)
    if remote_branch_exists(roadmap_dir, branch, remote):
        print(f"branch {branch} already exists on {remote} (an earlier run was interrupted); "
              f"opening the pull request for it rather than rewriting it")
    else:
        proc = _run(["git", "push", remote, f"HEAD:refs/heads/{branch}"], roadmap_dir, check=False)
        if proc.returncode != 0:
            # Most likely a peer created the same branch between the check and the push. That is fine:
            # fall through and let the pull-request step reconcile.
            print(f"create-only push declined ({proc.stderr.strip()[:200]}); reconciling instead")

    # Re-check between push and create: another worker may have opened the PR for this exact window
    # in the meantime, and the branch name is deterministic so it would be the same branch.
    # Deliberately the bare branch name, not `owner:branch`: the question is whether ANYONE has
    # already opened a pull request for this window, and the branch name is a pure function of the
    # window, so a peer publishing from their own fork must count.
    pr = existing_pr(branch)
    # `--head owner:branch` for creation, though, so `gh` looks for the branch on the fork rather
    # than on the canonical repository, where it does not exist.
    head = f"{fork_owner}:{branch}" if fork_owner else branch
    if pr is not None and (pr.get("state") or "").upper() == "OPEN":
        print(f"another worker opened it first: {pr['url']}")
        return EX_NOPROGRESS

    out = gh.gh([
        "pr", "create", "--repo", gh.ROADMAP_REPO, "--base", "main", "--head", head,
        "--title", title, "--body", body,
    ])
    print(out.strip())
    return 0
